# Generated by Django 3.1.1 on 2020-09-23 04:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indent_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_material', models.CharField(blank=True, max_length=100, null=True)),
                ('material_image', models.ImageField(upload_to='')),
                ('unit_price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_description', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_file', models.ImageField(upload_to='')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('from_node', models.CharField(blank=True, max_length=100, null=True)),
                ('to_node', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('breadth', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('task_created_on', models.DateField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.project_plan')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='Users_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=300)),
                ('address_proof', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('profile_completed_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_created_by', to='superrestapp.user_profile')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated_by', to='superrestapp.user_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower', models.FloatField()),
                ('machinary', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_at', models.DateField()),
                ('material_used', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.user')),
                ('task_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateField()),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='superrestapp.user')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='superrestapp.user')),
                ('task_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.user'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Profile',
            fields=[
                ('project_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_location', models.CharField(blank=True, max_length=100, null=True)),
                ('project_status', models.BooleanField(default=False)),
                ('project_description', models.CharField(blank=True, max_length=100, null=True)),
                ('project_created_on', models.DateField()),
                ('project_updated_on', models.DateField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.project')),
                ('project_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to='superrestapp.user')),
                ('project_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_updated_by', to='superrestapp.user')),
                ('project_users', models.ManyToManyField(to='superrestapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Profile',
            fields=[
                ('organization_profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_address', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_logo', models.ImageField(upload_to='')),
                ('organization_created_on', models.DateField()),
                ('organization_updated_on', models.DateField()),
                ('organization_status', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.organization')),
                ('organization_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='superrestapp.user')),
                ('organization_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='superrestapp.user')),
                ('organization_users', models.ManyToManyField(to='superrestapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Materials_Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateField()),
                ('received', models.BooleanField(default=False)),
                ('materials', models.ManyToManyField(to='superrestapp.Indent_Request')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='superrestapp.user')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user_id', to='superrestapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Indent_Response_To_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.IntegerField()),
                ('received_at', models.DateField()),
                ('dispatched_at', models.DateField()),
                ('dispatched_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='superrestapp.user')),
                ('received_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to='superrestapp.user')),
                ('requested_material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.material')),
            ],
        ),
        migrations.AddField(
            model_name='indent_request',
            name='required_material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.material'),
        ),
        migrations.AddField(
            model_name='indent_request',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.task'),
        ),
    ]
