# Generated by Django 3.1.1 on 2020-10-05 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_email', models.CharField(blank=True, max_length=254, null=True)),
                ('organization_address', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('organization_created_on', models.DateField(blank=True, null=True)),
                ('organization_updated_on', models.DateField(blank=True, null=True)),
                ('organization_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_location', models.CharField(blank=True, max_length=100, null=True)),
                ('project_status', models.BooleanField(default=False)),
                ('project_description', models.CharField(blank=True, max_length=100, null=True)),
                ('project_created_on', models.DateField(blank=True, null=True)),
                ('project_updated_on', models.DateField(blank=True, null=True)),
                ('organization_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_project_id', to='superrestapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=300)),
                ('address_proof', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('profile_completed_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_created_by', to='superrestapp.user_profile')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated_by', to='superrestapp.user_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='superrestapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to='superrestapp.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_updated_by', to='superrestapp.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_users',
            field=models.ManyToManyField(blank=True, related_name='project_users', to='superrestapp.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='superrestapp.user'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='superrestapp.user'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_users',
            field=models.ManyToManyField(blank=True, related_name='organization_users', to='superrestapp.User'),
        ),
    ]
