# Generated by Django 3.1.1 on 2020-10-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superrestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('store_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_created_by', to='superrestapp.user')),
                ('store_organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_organization_id', to='superrestapp.project')),
                ('store_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_project_id', to='superrestapp.project')),
                ('store_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_updated_by', to='superrestapp.user')),
                ('store_users', models.ManyToManyField(blank=True, related_name='store_users', to='superrestapp.User')),
            ],
        ),
    ]
