# Generated by Django 3.1.1 on 2020-10-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superrestapp', '0002_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
