# Generated by Django 3.1.1 on 2020-11-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superrestapp', '0006_auto_20201005_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_description', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_template', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_created_by', to='superrestapp.user')),
                ('plan_organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_organization_id', to='superrestapp.organization')),
                ('plan_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_project_id', to='superrestapp.project')),
                ('plan_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_updated_by', to='superrestapp.user')),
            ],
        ),
    ]
